name            'chefdm-selenium'
maintainer      'Philip Hutchins'
maintainer_email  'philip.hutchins@dealermatch.biz'
description       'Installs DM monitors that use selenium'
version           '0.0.1'

depends 'base'
depends 'selenium'
depends 'rvm'
depends 'apache2'
depends 'harviewer'
